### ISSUE TITLE
npm install returns 404

### ISSUE THREAD

**Issue by atermenji** [arkes/hangar-factory-girl#1]
When using `npm install hangar-factory-girl` I see

```
npm ERR! 404 Not Found: hangar-factory-girl
npm ERR! 404
npm ERR! 404 'hangar-factory-girl' is not in the npm registry.
```

**Comment by arkes** [comment]
Hey, I would suggest you can use this repo it's written by Hangar
https://github.com/faradayio/hangarjs

After if really want to use hangar-factory-girl, I can add it to rpm, up to you

**Comment by atermenji** [comment]
@arkes already used, thanks
